# Generated by Django 4.1.2 on 2022-11-19 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0006_alter_order_customer_alter_shippingaddress_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_published',
            new_name='is_active',
        ),
    ]
